### ISSUE TITLE
Expose PG3&4 within the interface

### ISSUE THREAD

**Issue by frizman21** [LuciferAndDiablo/NTC-C.H.I.P.-JavaGPIOLib#1]
I'd like to take advantage of ports 43 and 44 on the CHIP pro, but these don't seem to be mapped through the API (Port G, pin J1 and H1). I noticed Ports B thru F are mapped. Could we get these two G ports also mapped?

Information above pulled from [R8 v1.0.1 specification](https://github.com/NextThingCo/CHIP_Pro-Hardware/blob/master/Datasheets/GR8_Datasheet_v1.01.pdf)

**Comment by DenisLAD** [comment]
Could you try to use 0.2.2 branch.
But cant test it, because I have no actual memory mapping datasheet for GR8.

All information are obtained from http://linux-sunxi.org/R8

Most of parameters are the same as for R8.

**Comment by frizman21** [comment]
`ChipPro.I.open(); `

causes the following exception. Please advise...
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at free.lucifer.chiplib.modules.I2C.open(I2C.java:37)
	at free.lucifer.chiplib.boards.AXP209.open(AXP209.java:43)
	at free.lucifer.chiplib.ChipPro.open(ChipPro.java:139)
        at [my code]
Caused by: java.lang.IllegalArgumentException: Can't create an instance of class com.sun.jna.IntegerType, requires a no-arg constructor: java.lang.InstantiationException: com.sun.jna.IntegerType
	at com.sun.jna.NativeMappedConverter.defaultValue(NativeMappedConverter.java:55)
	at com.sun.jna.NativeMappedConverter.<init>(NativeMappedConverter.java:44)
	at com.sun.jna.NativeMappedConverter.getInstance(NativeMappedConverter.java:32)
	at com.sun.jna.Native.register(Native.java:1610)
	at com.sun.jna.Native.register(Native.java:1529)
	at free.lucifer.chiplib.natives.CLib.<clinit>(CLib.java:36)
	... 8 more
```

Also, I noticed the Led helper class no longer works with the ChipPro Pin class.

**Comment by DenisLAD** [comment]
Committed a little bit different implementation.
